creation_rules:
  - path_regex: secrets/.*\.(yaml|yml|json|env)$
    age:
      - age1et5e35lqkzlnk9gpnkz0p5xmxqcuxpl8s75kr7w048sg7je48yys0z4xyp
      - age1vezw3ppgekf5aznk9zv0gjc6u5ye2k3gza95wpw0xcrgsg4f29esg6h7v3
      - age1p9myvxfdgxd5ch42wknkf8kxxsum0n44vyq2ff4tl0uexg483aeqh22kpg
      - age1pdkc2f3hzrfzm2rjhsnx8z63s2gwca8sj4uf5je2l3fwlas373uqcza2u5
